export const cars = [
  {
    model: "Toyota Hiace GL 2016",
    type: "van",
    seats: 12,
    location: "Dhaka",
    status: "Available",
  },
  {
    model: "Toyota Hiace GL 2016",
    type: "van",
    seats: 12,
    location: "Rangpur",
    status: "Available",
  },
  {
    model: "Avanza 2008",
    type: "suv",
    seats: 7,
    location: "Dhaka",
    status: "Available",
  },
  {
    model: "Avanza 2008",
    type: "suv",
    seats: 7,
    location: "Barishal",
    status: "Available",
  },
  {
    model: "Toyota Corolla Hatchback SE 2022",
    type: "suv",
    seats: 7,
    location: "Dhaka",
    status: "Available",
  },
  {
    model: "Toyota Corolla Hatchback SE 2022",
    type: "suv",
    seats: 7,
    location: "Sylhet",
    status: "Available",
  },
  {
    model: "Toyota Hiace GL 2016",
    type: "van",
    seats: 12,
    location: "Dhaka",
    status: "Available",
  },
];
